spring.application.name=jm-proposal
spring.datasource.url=jdbc:postgresql://localhost:5432/job_matrix_local
spring.datasource.username=job_matrix
spring.datasource.password=job_matrix
spring.datasource.driver-class-name =org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10

spring.profiles.active=local

#kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.proposal-submitted=proposal-submitted
