package com.jobmatrix.jm_proposal.serviceimpl;

import com.jobmatrix.jm_proposal.dto.ProposalSubmissionDTO;
import com.jobmatrix.jm_proposal.entity.ProposalSubmission;
import com.jobmatrix.jm_proposal.exception.FreelancerNotFoundException;
import com.jobmatrix.jm_proposal.repository.FreelancerRepository;
import com.jobmatrix.jm_proposal.repository.ProposalRepository;
import com.jobmatrix.jm_proposal.service.ProposalService;
import lombok.RequiredArgsConstructor;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class ProposalServiceImpl implements ProposalService {

    private final ProposalRepository proposalRepository;
    private final FreelancerRepository freelancerRepository;
    private final ModelMapper modelMapper;

    @Override
    @Transactional
    public ProposalSubmission submitProposal(ProposalSubmissionDTO proposalRequest) {
        // Create a new entity and manually set the fields to avoid any ID mapping issues
        ProposalSubmission proposal = ProposalSubmission.builder()
                .jobPostingId(proposalRequest.getJobPostingId())
                .freelancerId(proposalRequest.getFreelancerId())
                .clientId(proposalRequest.getClientId())
                .proposedBidAmount(proposalRequest.getProposedBidAmount())
                .coverLetter(proposalRequest.getCoverLetter())
                // ID will be generated by the database
                .build();
        
        return proposalRepository.save(proposal);
    }

    @Override
    public List<ProposalSubmission> getProposalsByFreelancerId(UUID freelancerId) {
        // Check if the freelancer exists
        if (freelancerRepository.findById(freelancerId).isEmpty()) {
            throw new FreelancerNotFoundException(freelancerId);
        }
        List<ProposalSubmission> proposals = proposalRepository.findByFreelancerId(freelancerId);
        // Fetch proposals for the freelancer
        return proposals;
    }
}
